apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:l+mBd/HzX0cYPYQtZ4MXq4iJGi6BRjwt,iv:icc++SZmYGuhRJgEmqzi19sj5hsww3S9VrLaRvkZ1aE=,tag:FJtfD9We5eTHWlTW8pJ/HA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:P4rTqGuTuDW+CSn/348XmbD4rG4c651aqvIqiSBwFF0ggQ3qYA==,iv:mQ7JGhMK7fZ4s0MSp7G4fF/u2XQBCL0tpt0SxTZmTeg=,tag:5WgMp4kX4g3fQUnssScVRg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:YIW2LuRDiBSeulWMpMbukMk=,iv:Yvk0DWp80O6RnOrqXeffwLjXvm584Kzl08LNj1/w9XY=,tag:TzkH3JbmwzXD7xzyiaE54Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jtcha7rxg4nghcpu2vudnetplf5qsrt058kf9fvn4pkmdyf2a4fs84quhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZE9qUTMyUzZFQVU3dHNV
            emQrWTlpYmVSN3N6YWlZeFdZc1hUYitJb1ZVCjdiTWhjd0ZLTDZuL0dsRFdjNW83
            NkNaS0RDT2gwS0JHQWdqUDYzcFBHMlkKLS0tIEUrdEx0dFBUam5PTEpIS3REblVU
            aHdqTGNiVjdlcjJXWWNkRmxkZXhOMFUKMCW3qg+Ys8CHmBruZ2Q1OhFMczQJmBpy
            q1jFFxl9unP7c5im3fpM8q1buh2x8n7q2Qc77aZcRXzgefR88DxAPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-11T00:07:43Z"
    mac: ENC[AES256_GCM,data:e6QxGOscMGXjfkHE8GurvEJuZHXADWE9eMe3zjg4svUOXRtmYOx/9OAQXKYzb7Aqb0zD60gW3/niLOybXYxeNVGfdYqm4nfYWfTJ1MuVtvHPQa0va5iu7d/dV+2X6qbiFBYjMykhR224z8GKJR1bJaxiQpLi1rxmn+b9PXM+bp4=,iv:mPRRVZOsWBhkKxcQf4soxMb6gl5EwTvBebfzRuQBJR8=,tag:AN6HTs6AKrb6LGvJkC+k1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
