---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1jtcha7rxg4nghcpu2vudnetplf5qsrt058kf9fvn4pkmdyf2a4fs84quhj
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1jtcha7rxg4nghcpu2vudnetplf5qsrt058kf9fvn4pkmdyf2a4fs84quhj
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1jtcha7rxg4nghcpu2vudnetplf5qsrt058kf9fvn4pkmdyf2a4fs84quhj
