---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "192.168.50.49"
  METALLB_LB_RANGE: "192.168.50.50-192.168.50.60"
  METALLB_K8S_GATEWAY_ADDR: "192.168.50.50"
  METALLB_INGRESS_ADDR: "192.168.50.51"
